// Core game configuration constants
export const GAME_CONFIG = {
  SHIPS_PER_PLAYER: 20,
  PLANETS_PER_PLAYER: 5,
  SHIPS_PER_PLANET: 4,
  HAND_SIZE: 8,
  FOREIGN_COLONIES_TO_WIN: 5,
  HOME_COLONIES_FOR_POWER: 3,
  MAX_SHIPS_IN_GATE: 4,
  MAX_ALLY_SHIPS: 4,
  NEGOTIATION_TIMER_SECONDS: 60,
  DEAL_FAILED_SHIP_PENALTY: 3,
  MIN_PLAYERS: 3,
  MAX_PLAYERS: 5,
  FLARES_IN_DECK: 10,
  REGROUP_SHIPS_FROM_WARP: 1,
  MAX_SHIPS_TO_RECOLONIZE: 4,
} as const;
